brew "coreutils"
brew "fd"
brew "gh"
brew "git"
brew "grep"
brew "grip"
brew "ripgrep"
brew "shfmt"
tap "d12frosted/emacs-plus"
brew "emacs-plus@29", args: ["with-ctags", "with-dbus", "with-mailutils", "with-xwidgets", "with-imagemagick", "with-native-comp", "with-poll"]
