[tools]
go = "1.24.0"
elixir = "1.18.3-otp-27"
erlang = "27.3"
python = "3.13.3"
java = "temurin-21.0.6+7.0.LTS"
uv = "latest"
node = "24.3.0"

[settings]
idiomatic_version_file_enable_tools = ["node"]
