[tools]
go = "1.24.0"
poetry = "2.1.1"
elixir = "1.18.2-otp-27"
erlang = "27.2"
terraform = "1.10.5"
node = "23.8.0"
python = "3.13.2"
java = "temurin-23.0.2"
usage = "2.0.5"
shellcheck = "0.10.0"
spring-boot = "3.4.2"
maven = "3.9.9"
ruby = "3.4.2"
quarkus = "3.18.3"
