[tools]
go = "1.21.3"
poetry = "1.8.3"
elixir = "1.17.2-otp-27"
erlang = "27.0"
terraform = "1.10.4"
"pipx:erikbern/git-of-theseus" = "latest"
node = "22.7.0"
"cargo:cargo-binstall" = "1.6.9"
"cargo:diffedit3" = "0.4.0"
python = "3.13.0"
usage = "1.7.4"
java = "temurin-23.0.1+11"
shellcheck = "0.10.0"
spring-boot = "3.4.1"
gradle = "8.12.0"
maven = "3.9.9"
ruby = "3.4.1"
quarkus = "3.17.6"

[settings]
experimental = true
