[tools]
go = "1.21.3"
poetry = "1.8.3"
elixir = "1.17.2-otp-27"
erlang = "27.0"
terraform = "1.4.2"
"pipx:erikbern/git-of-theseus" = "latest"
node = "22.7.0"
"cargo:cargo-binstall" = "1.6.9"
"cargo:diffedit3" = "0.4.0"
python = "3.13.0"
usage = "0.3.0"
java = "corretto-17.0.13.11.1"
shellcheck = "0.10.0"
spring-boot = "3.3.5"
gradle = "8.10.2"
maven = "3.9.9"

[settings]
experimental = true
