[tools]
go = "1.21.3"
python = "3.12.3"
poetry = "1.7.1"
elixir = "1.17.1-otp-27"
erlang = "27.0"
java = "22.0.0"
terraform = "1.4.2"
perl = "5.38.2"
shellcheck = "0.10.0"
usage = "0.3.0"
"pipx:erikbern/git-of-theseus" = "latest"
node = "22.0.0"
"cargo:cargo-binstall" = "1.6.9"
"cargo:diffedit3" = "0.4.0"

[settings]
experimental = true
