[tools]
go = "1.21.3"
python = "3.12.3"
poetry = "1.7.1"
elixir = "1.16.2-otp-26"
erlang = "26.2.3"
java = "22.0.0"
terraform = "1.4.2"
perl = "5.38.2"
shellcheck = "0.9.0"
usage = "latest"
"pipx:erikbern/git-of-theseus" = "latest"

[settings]
experimental = true
