[tools]
go = "1.24.0"
elixir = "1.18.3-otp-27"
erlang = "27.3"
python = "3.13.2"
java = "temurin-21.0.6+7.0.LTS"
shellcheck = "0.10.0"
spring-boot = "3.4.2"
maven = "3.9.9"
uv = "0.6.1"
node = "23.9.0"
gradle = "8.13.0"
